# Generated by Django 6.0.1 on 2026-02-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playsession',
            unique_together={('session_key', 'story_id')},
        ),
        migrations.AlterField(
            model_name='playsession',
            name='session_key',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.RemoveField(
            model_name='playsession',
            name='created_at',
        ),
    ]
