# Generated by Django 6.0.1 on 2026-02-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_playsession_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playsession',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='playsession',
            name='session_key',
            field=models.CharField(max_length=255),
        ),
    ]
